Software_Information:
  author: "AuroBreeze"
  version: "1.1.0"
  update: "2024-11-22"
  license: "MIT"
  github: "https://github.com/AuroBreeze/Z-xinAnswerAutomatic"
  blog: "https://blog.aurobreeze.top/"
Basic_Information:
  username: "2024413493"
  password: "2024413493"
  api_key: ""
Job_Information:
  Interaction_mode: 0 # 0: 自动模式，1: 交互模式
  Homework: 0 # 0. 课后作业 3. 课程实验 2. 课堂作业 1. 课前预习
  Examination: 0 # 0. 不使用 1. 期中考试 2. 期末考试
  Answer_mode: 0 # 0. 自动答题 1. AI答题